# NumPy Initialization

In [1]:
import numpy

In [2]:
numpy.array([1, 2, 3])

array([1, 2, 3])

In [3]:
from numpy import *

In [4]:
array([1, 2, 3])

array([1, 2, 3])

In [2]:
import numpy as np
np.array([1, 2, 3])

array([1, 2, 3])

In [6]:
np.__version__

'1.19.2'

In [7]:
array1 = np.arange(100000)

In [8]:
array2 = list(range(100000))

In [9]:
%time for i in range(10): my_array1 = array1*2

Wall time: 3 ms


In [10]:
%time for i in range(10): my_array2 = [x*2 for x in array2]

Wall time: 179 ms


In [ ]:
help()


Welcome to Python 3.8's help utility!

If this is your first time using Python, you should definitely check out
the tutorial on the Internet at https://docs.python.org/3.8/tutorial/.

Enter the name of any module, keyword, or topic to get help on writing
Python programs and using Python modules.  To quit this help utility and
return to the interpreter, just type "quit".

To get a list of available modules, keywords, symbols, or topics, type
"modules", "keywords", "symbols", or "topics".  Each module also comes
with a one-line summary of what it does; to list the modules whose name
or summary contain a given string such as "spam", type "modules spam".



In [3]:
help(np.sort)

Help on function sort in module numpy:

sort(a, axis=-1, kind=None, order=None)
    Return a sorted copy of an array.
    
    Parameters
    ----------
    a : array_like
        Array to be sorted.
    axis : int or None, optional
        Axis along which to sort. If None, the array is flattened before
        sorting. The default is -1, which sorts along the last axis.
    kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
        Sorting algorithm. The default is 'quicksort'. Note that both 'stable'
        and 'mergesort' use timsort or radix sort under the covers and, in general,
        the actual implementation will vary with data type. The 'mergesort' option
        is retained for backwards compatibility.
    
        .. versionchanged:: 1.15.0.
           The 'stable' option was added.
    
    order : str or list of str, optional
        When `a` is an array with fields defined, this argument specifies
        which fields to compare first, second, etc.  A si

In [4]:
from numpy import doc

In [5]:
help(doc)

Help on package numpy.doc in numpy:

NAME
    numpy.doc

DESCRIPTION
    Topical documentation
    
    The following topics are available:
    
    - basics
    - broadcasting
    - byteswapping
    - constants
    - creation
    - dispatch
    - glossary
    - indexing
    - internals
    - misc
    - structured_arrays
    - subclassing
    - ufuncs
    
    You can view them by
    
    >>> help(np.doc.TOPIC)                                      #doctest: +SKIP

PACKAGE CONTENTS
    basics
    broadcasting
    byteswapping
    constants
    creation
    dispatch
    glossary
    indexing
    internals
    misc
    structured_arrays
    subclassing
    ufuncs

DATA
    __all__ = ['basics', 'broadcasting', 'byteswapping', 'constants', 'cre...

FILE
    d:\anaconda\lib\site-packages\numpy\doc\__init__.py




In [6]:
help(np.doc.basics)

Help on module numpy.doc.basics in numpy.doc:

NAME
    numpy.doc.basics

DESCRIPTION
    Array basics
    
    Array types and conversions between types
    
    NumPy supports a much greater variety of numerical types than Python does.
    This section shows which are available, and how to modify an array's data-type.
    
    The primitive types supported are tied closely to those in C:
    
    .. list-table::
        :header-rows: 1
    
        * - Numpy type
          - C type
          - Description
    
        * - `np.bool_`
          - ``bool``
          - Boolean (True or False) stored as a byte
    
        * - `np.byte`
          - ``signed char``
          - Platform-defined
    
        * - `np.ubyte`
          - ``unsigned char``
          - Platform-defined
    
        * - `np.short`
          - ``short``
          - Platform-defined
    
        * - `np.ushort`
          - ``unsigned short``
          - Platform-defined
    
        * - `np.intc`
          - ``int``

In [3]:
np.lookfor('arange')

Search results for 'arange'
---------------------------
numpy.arange
    Return evenly spaced values within a given interval.
numpy.ma.arange
    Return evenly spaced values within a given interval.
numpy.add
    Add arguments element-wise.
numpy.cov
    Estimate a covariance matrix, given data and weights.
numpy.dot
    Dot product of two arrays. Specifically,
numpy.gcd
    Returns the greatest common divisor of ``|x1|`` and ``|x2|``
numpy.ix_
    Construct an open mesh from multiple sequences.
numpy.lcm
    Returns the lowest common multiple of ``|x1|`` and ``|x2|``
numpy.mod
    Return element-wise remainder of division.
numpy.pad
    Pad an array.
numpy.put
    Replaces specified elements of an array with given values.
numpy.who
    Print the NumPy arrays in the given dictionary.
numpy.amax
    Return the maximum of an array or maximum along an axis.
numpy.amin
    Return the minimum of an array or minimum along an axis.
numpy.clip
    Clip (limit) the values in an array.
numpy.dia

In [6]:
np?

In [ ]:
np.arange?

In [7]:
np.arange??

In [ ]:
np.arange() 

In [ ]:
np.arange