# Data Types In NumPy

In [1]:
import numpy as np

In [2]:
array_4 = np.array(list(range(10)))
array_44

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.array(list(range(10)), dtype=np.float64)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [5]:
array_5 = np.array(list(range(10)), dtype = np.int32)
array_5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
array_5.dtype

dtype('int32')

In [8]:
array_4.dtype

dtype('int32')

In [9]:
np.array(list(range(10)), dtype=np.float64).dtype

dtype('float64')

In [10]:
array_6 = array_4.astype(np.float64)
print(array_6)
print(array_6.dtype)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
float64


In [12]:
np.array(list(range(10)), dtype=np.float64).astype(np.int32).dtype

dtype('int32')

In [13]:
array8 = np.array([3.5, -1.5, -2.5, 0.5, 12.6, 10.8])
array8

array([ 3.5, -1.5, -2.5,  0.5, 12.6, 10.8])

In [14]:
array9 = array8.astype(np.int64)
array9

array([ 3, -1, -2,  0, 12, 10], dtype=int64)

In [15]:
num_strings = np.array(['1', '-2', '3', '4'], dtype=np.string_)
num_strings

array([b'1', b'-2', b'3', b'4'], dtype='|S2')

In [16]:
num_array_int32 = num_strings.astype(np.int32)
num_array_int32

array([ 1, -2,  3,  4])

In [17]:
num_array_float = num_strings.astype(np.float)
num_array_float

array([ 1., -2.,  3.,  4.])

In [18]:
int_array = np.arange(15)
int_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
float_type = np.array([1.5, 1.7, 1.9, 1.11, 1.13], dtype=np.float64)
float_type

array([1.5 , 1.7 , 1.9 , 1.11, 1.13])

In [20]:
int_array_float = int_array.astype(float_type.dtype)
int_array_float

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14.])

In [21]:
empty_uint64 = np.empty(3, dtype='u8')
empty_uint64

array([     102470321408,                 0, 32651548270133250],
      dtype=uint64)