# Pseudorandom Number Generation

In [1]:
import numpy as np

In [2]:
samples1 = np.random.randn(5)
samples1

array([-0.1208589 ,  0.36763197,  0.74624135,  0.14483832, -0.49366139])

In [3]:
np.random.randn()

-0.6276936616165304

In [4]:
samples2 = np.random.randn(2, 3)
samples2

array([[ 0.28053847, -1.97382182,  0.6175872 ],
       [-0.39817975, -0.43871712, -0.00680332]])

In [5]:
np.random.randn(2, 3, 2)

array([[[-0.02988336, -0.52463367],
        [ 0.71915693,  0.53968463],
        [-0.2886855 ,  0.14899943]],

       [[-0.37784048,  2.15909912],
        [-0.05756148, -1.17807834],
        [-2.33285954, -0.59077453]]])

In [6]:
samples3 = np.random.normal(size=(4, 4))
samples3

array([[-1.55405198, -0.23946783,  0.37982544, -0.66248583],
       [-0.79581186,  0.42484339, -0.16856019, -0.45623706],
       [-0.0840042 ,  0.88406042,  0.78812467,  0.69788123],
       [-0.75341436,  0.30137972,  0.1307087 ,  0.33266827]])

In [1]:
from numpy.random import *

In [2]:
seed(1234)

In [30]:
seed(1234)
x = randn(10)
x

array([ 0.47143516, -1.19097569,  1.43270697, -0.3126519 , -0.72058873,
        0.88716294,  0.85958841, -0.6365235 ,  0.01569637, -2.24268495])

In [3]:
y =rand(10)
y

array([0.19151945, 0.62210877, 0.43772774, 0.78535858, 0.77997581,
       0.27259261, 0.27646426, 0.80187218, 0.95813935, 0.87593263])

In [5]:
z = randint(10, 20)
z

15

In [6]:
zs = randint(10, 30, size=(2, 5), dtype='int64' ) # use float to convert integers in to float values
zs

array([[26, 19, 25, 28, 26],
       [22, 15, 12, 16, 13]], dtype=int64)

In [7]:
randint(10, 30).reshape(2, 10)

AttributeError: 'int' object has no attribute 'reshape'

In [15]:
randn(10).reshape(2, 5)

array([[ 1.88713275, -1.75646206, -1.78114751,  2.29022655, -1.50568522],
       [-1.08080767,  0.51369502,  1.09898119,  0.46008495,  0.20268955]])

In [16]:
rand = RandomState(1234)

In [17]:
rand.rand(10)

array([0.19151945, 0.62210877, 0.43772774, 0.78535858, 0.77997581,
       0.27259261, 0.27646426, 0.80187218, 0.95813935, 0.87593263])

In [18]:
rand.randint(10)

8

In [19]:
rand.randn(10)

array([ 2.00254961,  0.01086208, -0.86924706,  1.4249841 ,  0.1458091 ,
        2.89409095, -0.30426018,  0.861661  , -0.68992667,  0.18749737])

In [20]:
rand.normal(10)

10.604308742162978

In [21]:
rand.uniform(10)

4.137596710960803