# Indexing and Slicing

In [1]:
import numpy as np

In [2]:
array1 = np.array(np.arange(20))
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [3]:
array1[2]

2

In [5]:
array1[10:15]

array([10, 11, 12, 13, 14])

In [6]:
array1[10:15] = 14

In [7]:
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 14, 14, 14, 14, 14, 15, 16,
       17, 18, 19])

In [8]:
array2 = array1[10:15]
array2

array([14, 14, 14, 14, 14])

In [9]:
array2[2] = 30

In [10]:
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 14, 14, 30, 14, 14, 15, 16,
       17, 18, 19])

In [11]:
array2[:] = 50

In [12]:
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 50, 50, 50, 50, 50, 15, 16,
       17, 18, 19])

In [15]:
array2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
array2d[1]

array([4, 5, 6])

In [17]:
array2d[1][2]

6

In [18]:
array2d[1, 2]

6

In [19]:
array3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
array3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [20]:
array3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
first_array = array3d[0].copy()
first_array

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
array3d[0] = 60

In [23]:
array3d

array([[[60, 60, 60],
        [60, 60, 60]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [24]:
array3d[0] = first_array

In [25]:
array3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [26]:
array3d[0, 1]

array([4, 5, 6])

In [28]:
first_a = array3d[0]

In [29]:
first_a[1]

array([4, 5, 6])

In [30]:
array2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
array2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
array2d[:2, 1]

array([2, 5])

In [33]:
array2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [35]:
array2d[1, :2]

array([4, 5])

In [36]:
array2d[:, 1:2]

array([[2],
       [5],
       [8]])

In [37]:
array2d[:2, 1:] = 20
array2d

array([[ 1, 20, 20],
       [ 4, 20, 20],
       [ 7,  8,  9]])

In [38]:
array3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [39]:
array3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
array3d[0][0]

array([1, 2, 3])

In [41]:
array3d[0][:, 1:]

array([[2, 3],
       [5, 6]])

In [42]:
array3d[0][:, :2]

array([[1, 2],
       [4, 5]])

In [43]:
y = array3d[1]
y

array([[ 7,  8,  9],
       [10, 11, 12]])

In [44]:
y[0]

array([7, 8, 9])

In [45]:
y[:, :2]

array([[ 7,  8],
       [10, 11]])