# Boolean Indexing

In [1]:
import numpy as np

In [2]:
days = np.array(['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun', 'Thu', 'Thu'])
days

array(['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun', 'Thu',
       'Thu'], dtype='<U3')

In [3]:
data = np.random.randn(10, 4)
data

array([[ 0.48806782, -2.45046071, -0.51818333, -1.45871172],
       [-0.0613477 ,  0.8308607 ,  0.09922152,  0.98912745],
       [ 0.53477836, -0.93688299, -2.09243621,  0.52828142],
       [-1.04345958, -1.0481358 ,  1.2696092 , -0.10741584],
       [-0.68026828,  0.98088998,  0.85177922, -1.27499814],
       [-1.21808615,  0.33724649, -0.36068433, -0.29507253],
       [ 0.04457884, -0.89596789, -0.25695732, -1.30245996],
       [-1.11380715,  0.20001238,  1.16422775, -0.34262239],
       [-0.67132395, -0.80409242, -1.05868473, -0.11754513],
       [ 0.04055683, -0.75262135, -0.12225205, -1.62781047]])

In [4]:
days == 'Sun'

array([ True, False, False, False, False, False, False,  True, False,
       False])

In [5]:
data[days=='Sun']

array([[ 0.48806782, -2.45046071, -0.51818333, -1.45871172],
       [-1.11380715,  0.20001238,  1.16422775, -0.34262239]])

In [6]:
data[days=='Sun', 1:]

array([[-2.45046071, -0.51818333, -1.45871172],
       [ 0.20001238,  1.16422775, -0.34262239]])

In [7]:
data[days=='Sun', 1]

array([-2.45046071,  0.20001238])

In [8]:
days != 'Sun'

array([False,  True,  True,  True,  True,  True,  True, False,  True,
        True])

In [9]:
~(days == 'Sun')                        # this symbol is used to negate the condition. 

array([False,  True,  True,  True,  True,  True,  True, False,  True,
        True])

In [10]:
data[~(days=='Sun')]

array([[-0.0613477 ,  0.8308607 ,  0.09922152,  0.98912745],
       [ 0.53477836, -0.93688299, -2.09243621,  0.52828142],
       [-1.04345958, -1.0481358 ,  1.2696092 , -0.10741584],
       [-0.68026828,  0.98088998,  0.85177922, -1.27499814],
       [-1.21808615,  0.33724649, -0.36068433, -0.29507253],
       [ 0.04457884, -0.89596789, -0.25695732, -1.30245996],
       [-0.67132395, -0.80409242, -1.05868473, -0.11754513],
       [ 0.04055683, -0.75262135, -0.12225205, -1.62781047]])

In [11]:
cond = (days=='Sun')
cond

array([ True, False, False, False, False, False, False,  True, False,
       False])

In [12]:
data[~cond]

array([[-0.0613477 ,  0.8308607 ,  0.09922152,  0.98912745],
       [ 0.53477836, -0.93688299, -2.09243621,  0.52828142],
       [-1.04345958, -1.0481358 ,  1.2696092 , -0.10741584],
       [-0.68026828,  0.98088998,  0.85177922, -1.27499814],
       [-1.21808615,  0.33724649, -0.36068433, -0.29507253],
       [ 0.04457884, -0.89596789, -0.25695732, -1.30245996],
       [-0.67132395, -0.80409242, -1.05868473, -0.11754513],
       [ 0.04055683, -0.75262135, -0.12225205, -1.62781047]])

In [13]:
multi_cond = (days=='Sun') | (days == 'Thu')
multi_cond

array([ True, False, False, False,  True, False, False,  True,  True,
        True])

In [14]:
data[multi_cond]

array([[ 0.48806782, -2.45046071, -0.51818333, -1.45871172],
       [-0.68026828,  0.98088998,  0.85177922, -1.27499814],
       [-1.11380715,  0.20001238,  1.16422775, -0.34262239],
       [-0.67132395, -0.80409242, -1.05868473, -0.11754513],
       [ 0.04055683, -0.75262135, -0.12225205, -1.62781047]])

In [15]:
data[data < 0] = 0                     # data and filter the data where the array elements are < 0 and assign 0 for them. 
data

array([[0.48806782, 0.        , 0.        , 0.        ],
       [0.        , 0.8308607 , 0.09922152, 0.98912745],
       [0.53477836, 0.        , 0.        , 0.52828142],
       [0.        , 0.        , 1.2696092 , 0.        ],
       [0.        , 0.98088998, 0.85177922, 0.        ],
       [0.        , 0.33724649, 0.        , 0.        ],
       [0.04457884, 0.        , 0.        , 0.        ],
       [0.        , 0.20001238, 1.16422775, 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.04055683, 0.        , 0.        , 0.        ]])

In [16]:
data[days != 'Sun'] = 0.5
data

array([[0.48806782, 0.        , 0.        , 0.        ],
       [0.5       , 0.5       , 0.5       , 0.5       ],
       [0.5       , 0.5       , 0.5       , 0.5       ],
       [0.5       , 0.5       , 0.5       , 0.5       ],
       [0.5       , 0.5       , 0.5       , 0.5       ],
       [0.5       , 0.5       , 0.5       , 0.5       ],
       [0.5       , 0.5       , 0.5       , 0.5       ],
       [0.        , 0.20001238, 1.16422775, 0.        ],
       [0.5       , 0.5       , 0.5       , 0.5       ],
       [0.5       , 0.5       , 0.5       , 0.5       ]])