# Fancy Indexing

In [1]:
import numpy as np

In [2]:
data = np.empty((10, 4))
data

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [3]:
for i in range(10):
    data[i]= i*2

data

array([[ 0.,  0.,  0.,  0.],
       [ 2.,  2.,  2.,  2.],
       [ 4.,  4.,  4.,  4.],
       [ 6.,  6.,  6.,  6.],
       [ 8.,  8.,  8.,  8.],
       [10., 10., 10., 10.],
       [12., 12., 12., 12.],
       [14., 14., 14., 14.],
       [16., 16., 16., 16.],
       [18., 18., 18., 18.]])

In [4]:
list_int = [2, 1, 5, 9]

In [5]:
data[list_int]

array([[ 4.,  4.,  4.,  4.],
       [ 2.,  2.,  2.,  2.],
       [10., 10., 10., 10.],
       [18., 18., 18., 18.]])

In [6]:
list_neg_int = [-1, -2, -5]
data[list_neg_int]

array([[18., 18., 18., 18.],
       [16., 16., 16., 16.],
       [10., 10., 10., 10.]])

In [7]:
data_shape10x4 = np.arange(40).reshape((10, 4))
data_shape10x4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39]])

In [8]:
list1, list2 = [1, 2], [3, 3]

In [9]:
data_shape10x4[list1, list2]                # (1, 3), (2, 3)

array([ 7, 11])

In [10]:
list3, list4 = [3, 2, 5, 9], [1, 2, 3, 3]

In [11]:
data_shape10x4[list3, list4]                 # (3, 1), (2, 2), (5, 3), (9, 3)

array([13, 10, 23, 39])

In [12]:
data_shape10x4[[1, 5, 7, 2]]

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23],
       [28, 29, 30, 31],
       [ 8,  9, 10, 11]])

In [13]:
data_shape10x4[[1, 5, 7, 2]][:, [0, 3]]     # [:, [0, 3]] selecting all the rows and only the columns at index positions 0 and 3

array([[ 4,  7],
       [20, 23],
       [28, 31],
       [ 8, 11]])

In [14]:
data_shape10x4[[1, 5, 7, 2]][:, [0, 3, 1, 2]] # select all the rows and rearrange all the columns by selecting all the columns
                                              # at different positons. 

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])