# How To Save and Load In NumPy

In [1]:
import numpy as np

In [2]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.save('ARRAY_DATA', data)

In [4]:
np.load('ARRAY_DATA.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
x = np.arange(10)
y = np.arange(10, 20)

In [6]:
np.savez('ARRAYS_X&Y.npz', a=x, b=y)

In [8]:
values = np.load('ARRAYS_X&Y.npz')

In [9]:
values['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
values['b']

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [11]:
np.savez_compressed('ARRAYS_COM.npz', a=x, b=y)

In [12]:
arrays = np.load('ARRAYS_COM.npz')
arrays['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])