# Mathematical and Statistical Methods

In [1]:
import numpy as np

In [2]:
data = np.random.randn(6, 3)
data

array([[ 0.95767142,  0.65204958,  0.83457647],
       [-0.14309761, -0.60066967, -0.94635032],
       [ 0.35026067,  1.18702701,  0.80603217],
       [ 0.81414411,  1.26547221,  0.43484407],
       [-1.52573574, -1.08546377,  0.22946175],
       [-1.21899267, -2.01876162,  0.31048072]])

In [3]:
data.mean()

0.016830488146103977

In [4]:
data.min()

-2.0187616169866356

In [5]:
data.max()

1.2654722089185275

In [6]:
data.sum()

0.30294878662987157

In [7]:
data.sum(axis = 0)

array([-0.76574981, -0.60034626,  1.66904485])

In [8]:
data

array([[ 0.95767142,  0.65204958,  0.83457647],
       [-0.14309761, -0.60066967, -0.94635032],
       [ 0.35026067,  1.18702701,  0.80603217],
       [ 0.81414411,  1.26547221,  0.43484407],
       [-1.52573574, -1.08546377,  0.22946175],
       [-1.21899267, -2.01876162,  0.31048072]])

In [9]:
data[:, 0:1]

array([[ 0.95767142],
       [-0.14309761],
       [ 0.35026067],
       [ 0.81414411],
       [-1.52573574],
       [-1.21899267]])

In [10]:
data[:, 0:1].sum()

-0.7657498101143108

In [11]:
data.sum(axis = 1)

array([ 2.44429747, -1.6901176 ,  2.34331985,  2.51446038, -2.38173775,
       -2.92727356])

In [12]:
values = np.arange(5)
values

array([0, 1, 2, 3, 4])

In [13]:
values.cumsum()

array([ 0,  1,  3,  6, 10], dtype=int32)

In [14]:
values.std()

1.4142135623730951

In [16]:
matrix_array= np.array([np.arange(1, 5), np.arange(6, 10 ), np.arange(11, 15)])
matrix_array

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14]])

In [17]:
matrix_array.cumsum(axis=0)

array([[ 1,  2,  3,  4],
       [ 7,  9, 11, 13],
       [18, 21, 24, 27]], dtype=int32)

In [18]:
matrix_array.cumsum(axis=1)

array([[ 1,  3,  6, 10],
       [ 6, 13, 21, 30],
       [11, 23, 36, 50]], dtype=int32)

In [19]:
matrix_array.cumprod(axis=1)

array([[    1,     2,     6,    24],
       [    6,    42,   336,  3024],
       [   11,   132,  1716, 24024]], dtype=int32)