# Arithmetic Operations In Ndarrays

In [1]:
import numpy as np

In [2]:
data1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
data1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [3]:
data1*data1

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [4]:
data1 + data1

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [5]:
data2 = data1*3
data2

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24]])

In [6]:
1/data1

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.2       , 0.16666667, 0.14285714, 0.125     ]])

In [7]:
data1**(2)

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]], dtype=int32)

In [9]:
data3 = np.array([[1, 2, 12, 4], [10, 11, 10, 10]])
data3

array([[ 1,  2, 12,  4],
       [10, 11, 10, 10]])

In [10]:
data1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
(data1 >= data3)

array([[ True,  True, False,  True],
       [False, False, False, False]])