# Universal Functions

In [1]:
import numpy as np

In [2]:
data = np.arange(5)
data

array([0, 1, 2, 3, 4])

In [3]:
np.sqrt(data)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [4]:
np.exp(data)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [5]:
np.max(data)

4

In [6]:
np.min(data)

0

In [7]:
data1= np.random.randn(5)
data1

array([ 0.98473747,  0.10682151,  1.6395337 , -1.43979152, -2.32251316])

In [8]:
data2 = np.random.randn(5)
data2

array([-0.81046273,  1.44323704, -0.94497024,  0.56227657, -1.14217954])

In [9]:
np.maximum(data1, data2)

array([ 0.98473747,  1.44323704,  1.6395337 ,  0.56227657, -1.14217954])

In [10]:
data3 = np.random.randn(10)*5
data3

array([-2.40481638,  2.22757407, -0.86444385,  3.40900003,  5.11289141,
       -4.95293498,  2.18851982, -0.93991344,  0.99218903,  9.12389303])

In [11]:
fraction, integral = np.modf(data3)

In [12]:
fraction

array([-0.40481638,  0.22757407, -0.86444385,  0.40900003,  0.11289141,
       -0.95293498,  0.18851982, -0.93991344,  0.99218903,  0.12389303])

In [13]:
integral

array([-2.,  2., -0.,  3.,  5., -4.,  2., -0.,  0.,  9.])

In [14]:
np.sqrt(data3)

<ipython-input-14-190fb2d5c10c>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(data3)


array([       nan, 1.49250597,        nan, 1.84634775, 2.26117036,
              nan, 1.47936467,        nan, 0.99608686, 3.02057826])

In [15]:
np.abs(data3)

array([2.40481638, 2.22757407, 0.86444385, 3.40900003, 5.11289141,
       4.95293498, 2.18851982, 0.93991344, 0.99218903, 9.12389303])

In [16]:
np.sqrt(np.abs(data3))

array([1.55074704, 1.49250597, 0.92975473, 1.84634775, 2.26117036,
       2.22551904, 1.47936467, 0.96949133, 0.99608686, 3.02057826])

In [17]:
np.square(data3)

array([ 5.78314184,  4.96208626,  0.74726317, 11.62128121, 26.14165856,
       24.5315649 ,  4.78961901,  0.88343728,  0.98443907, 83.24542407])

In [18]:
np.rint(data3)

array([-2.,  2., -1.,  3.,  5., -5.,  2., -1.,  1.,  9.])

In [19]:
data3

array([-2.40481638,  2.22757407, -0.86444385,  3.40900003,  5.11289141,
       -4.95293498,  2.18851982, -0.93991344,  0.99218903,  9.12389303])

In [20]:
np.ceil(data3)

array([-2.,  3., -0.,  4.,  6., -4.,  3., -0.,  1., 10.])

In [21]:
data4 = np.arange(10).reshape(2, 5)
data4

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [22]:
data5 = np.arange(5, 15).reshape(2, 5)
data5

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [23]:
np.add(data4, data5)

array([[ 5,  7,  9, 11, 13],
       [15, 17, 19, 21, 23]])

In [24]:
np.subtract(data5, data4)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [25]:
np.multiply(data4, data5)

array([[  0,   6,  14,  24,  36],
       [ 50,  66,  84, 104, 126]])

In [26]:
np.divide(data4, data5)

array([[0.        , 0.16666667, 0.28571429, 0.375     , 0.44444444],
       [0.5       , 0.54545455, 0.58333333, 0.61538462, 0.64285714]])

In [27]:
np.power(data4, data5)

array([[         0,          1,        128,       6561,     262144],
       [   9765625,  362797056,  956385313,          0, 1796636465]],
      dtype=int32)

In [28]:
print(' d4:\n',data4,'\n','and\n','d5:\n',data5)

 d4:
 [[0 1 2 3 4]
 [5 6 7 8 9]] 
 and
 d5:
 [[ 5  6  7  8  9]
 [10 11 12 13 14]]


In [29]:
np.greater(data4, data5) 

array([[False, False, False, False, False],
       [False, False, False, False, False]])

In [30]:
np.greater(data5, data4)

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])