# Conditional Logics in NumPy Arrays

In [1]:
import numpy as np

In [2]:
data_x = np.array(np.arange(5))
data_x

array([0, 1, 2, 3, 4])

In [3]:
data_y = np.array(np.arange(5, 10))
data_y

array([5, 6, 7, 8, 9])

In [4]:
cond = np.array([True, False, False, True, True])

In [5]:
result = [(x if c else y) for x, c, y in zip(data_x,  cond, data_y)]
result

[0, 6, 7, 3, 4]

In [6]:
result_where = np.where(cond, data_x, data_y)
result_where

array([0, 6, 7, 3, 4])

In [7]:
data_z = np.random.randn(10, 4)
data_z

array([[-0.31636329,  1.11820539,  1.30082551,  0.14750354],
       [ 0.2983498 , -1.09725841, -0.80070168, -0.68017896],
       [-0.41249709, -1.21975816,  0.65703449, -0.28505311],
       [-1.57571568, -0.65550633,  0.46237102, -0.13957305],
       [ 0.04765394, -0.40854095,  0.85610291,  0.83008119],
       [-0.3428456 , -0.71618246,  0.99196892, -1.04513739],
       [ 0.22167714,  0.99019177, -1.13803267, -0.22374813],
       [ 0.41551768,  0.54781642, -0.55926814,  0.45989446],
       [ 0.66278615,  1.39661009,  0.07770117, -1.15579995],
       [-1.38855253,  0.66447718, -0.24598968, -2.35613859]])

In [8]:
result_2 = np.where(data_z >0, 5, -5)
result_2

array([[-5,  5,  5,  5],
       [ 5, -5, -5, -5],
       [-5, -5,  5, -5],
       [-5, -5,  5, -5],
       [ 5, -5,  5,  5],
       [-5, -5,  5, -5],
       [ 5,  5, -5, -5],
       [ 5,  5, -5,  5],
       [ 5,  5,  5, -5],
       [-5,  5, -5, -5]])

In [9]:
result_2 = np.where(data_z >0, 5, data_z)
result_2

array([[-0.31636329,  5.        ,  5.        ,  5.        ],
       [ 5.        , -1.09725841, -0.80070168, -0.68017896],
       [-0.41249709, -1.21975816,  5.        , -0.28505311],
       [-1.57571568, -0.65550633,  5.        , -0.13957305],
       [ 5.        , -0.40854095,  5.        ,  5.        ],
       [-0.3428456 , -0.71618246,  5.        , -1.04513739],
       [ 5.        ,  5.        , -1.13803267, -0.22374813],
       [ 5.        ,  5.        , -0.55926814,  5.        ],
       [ 5.        ,  5.        ,  5.        , -1.15579995],
       [-1.38855253,  5.        , -0.24598968, -2.35613859]])