# Sorting in NumPy

In [1]:
import numpy as np

In [2]:
data = np.random.randn(10)
data

array([ 1.13580441,  0.51665936,  0.50280307,  0.64670954, -0.84257721,
        0.59715008,  1.93250004,  0.13069962,  0.89857931,  0.25354294])

In [3]:
data.sort()

In [4]:
data

array([-0.84257721,  0.13069962,  0.25354294,  0.50280307,  0.51665936,
        0.59715008,  0.64670954,  0.89857931,  1.13580441,  1.93250004])

In [5]:
data2= np.random.randn(10)
data2

array([ 1.33351209, -0.45611696, -2.20623734,  0.89385237,  0.2571922 ,
       -1.75678037, -1.3259173 , -1.30123928,  0.25245954, -0.39496957])

In [6]:
np.sort(data2)

array([-2.20623734, -1.75678037, -1.3259173 , -1.30123928, -0.45611696,
       -0.39496957,  0.25245954,  0.2571922 ,  0.89385237,  1.33351209])

In [7]:
matrix_data = np.random.randn(6, 3)
matrix_data

array([[ 1.688686  ,  1.09566081,  0.79616162],
       [ 0.16228502, -0.78090146,  1.36210778],
       [ 0.35207636,  0.41044506, -1.25627113],
       [-1.44876521,  1.28174944, -0.269161  ],
       [-0.01832029, -0.57427452, -0.06493418],
       [-0.82723478,  0.46245609,  0.45611131]])

In [8]:
matrix_data.sort(axis=-1)

In [9]:
matrix_data

array([[ 0.79616162,  1.09566081,  1.688686  ],
       [-0.78090146,  0.16228502,  1.36210778],
       [-1.25627113,  0.35207636,  0.41044506],
       [-1.44876521, -0.269161  ,  1.28174944],
       [-0.57427452, -0.06493418, -0.01832029],
       [-0.82723478,  0.45611131,  0.46245609]])

In [10]:
matrix_data.sort(axis=0)

In [11]:
matrix_data

array([[-1.44876521, -0.269161  , -0.01832029],
       [-1.25627113, -0.06493418,  0.41044506],
       [-0.82723478,  0.16228502,  0.46245609],
       [-0.78090146,  0.35207636,  1.28174944],
       [-0.57427452,  0.45611131,  1.36210778],
       [ 0.79616162,  1.09566081,  1.688686  ]])